local ui = require("harpoon.ui")
local mark = require("harpoon.mark")

-- vim.keymap.set("n","<leader>m", "<cmd>lua require('harpoon.mark').add_file()<CR>")
vim.keymap.set("n","<leader>m", function()
	mark.add_file()
	print("Add File")
end)
-- vim.keymap.set("n","<leader>M", "<cmd>lua require('harpoon.ui').toggle_quick_menu()<CR>")
vim.keymap.set("n","<leader>M", function()
	ui.toggle_quick_menu()
	print("Toggle UI")
end)
vim.keymap.set("n", "<space>h", function() ui.nav_file(1) end)
vim.keymap.set("n", "<space>j", function() ui.nav_file(2) end)
vim.keymap.set("n", "<space>k", function() ui.nav_file(3) end)
vim.keymap.set("n", "<space>l", function() ui.nav_file(4) end)

vim.keymap.set("n", "<space>H", function()
	vim.cmd("vsplit")
	ui.nav_file(1)
end)
vim.keymap.set("n", "<space>J", function()
	vim.cmd("vsplit")
	ui.nav_file(2)
end)
vim.keymap.set("n", "<space>K", function()
	vim.cmd("vsplit")
	ui.nav_file(3)
end)
vim.keymap.set("n", "<space>L", function()
	vim.cmd("vsplit")
	ui.nav_file(4)
end)
