-- -- Options
-- vim.cmd("let g:vimwiki_list = [{'path': '~/vimwiki/','syntax': 'markdown', 'ext': '.md'}]")
-- vim.cmd("let g:vimwiki_global_ext = 0")
-- vim.g.vimwiki_list = {{path = '~/Docs/Mywiki', syntax = 'markdown', ext = '.md'}}
-- vim.g.vimwiki_list = {{path='~/vimwiki/', syntax='vimwiki', ext=".wiki"}}
-- vim.g.vimwiki_global_ext = 0
-- -- Keybinds
-- vim.keymap.set("n", "<space>w",function () vim.cmd("VimwikiIndex") end)
-- vim.keymap.set("n", "<space>W",function ()
-- 	vim.cmd("vsplit")
-- 	vim.cmd("VimwikiIndex")
-- end)
-- vim.keymap.set("n", "<space>t",function () vim.cmd("e ~/vimwiki/todo.wiki") end)
-- vim.keymap.set("n", "<space>T",function ()
-- 	vim.cmd("vsplit")
-- 	vim.cmd("e ~/vimwiki/todo.wiki")
-- end)
