local nnoremap = require("jzdoot.keymap").nnoremap

vim.g.mapleader = ";"

nnoremap("<space>.", "<cmd>lua require('telescope.builtin').find_files()<cr>")
nnoremap("<space>m", "<cmd>Telescope harpoon marks<CR>")
nnoremap("<space>g", "<cmd>Telescope live_grep<CR>")
nnoremap("<leader>.", "<cmd>Telescope find_files<CR>")
nnoremap("<leader>t", "<cmd>term<CR>")
nnoremap("<leader>T", "<cmd>vsp<CR> :term<CR>")
nnoremap("<leader>l", "<cmd>tabnext<CR>")
nnoremap("<leader>h", "<cmd>tabprevious<CR>")
nnoremap("<leader>n", "<cmd>tabnew<CR>")
nnoremap("<leader>N", "<cmd>tabclose<CR>")
nnoremap("<leader>c", "<cmd>!code %:p:h<CR>")
nnoremap("<leader>C", "<cmd>cd %:p:h<CR>")
nnoremap("<leader>e", "<cmd>e ~/.config/nvim/init.vim<CR>")
nnoremap("<leader><F10>uo", "<cmd>PlugUpdate<CR> :CocUpdate<CR> :TSUpdate<CR>")
nnoremap("<leader><F10>so", "<cmd>source ~/.config/nvim/init.vim<CR>")
nnoremap("<leader>`", "<cmd>Ex<CR>")
nnoremap("<leader>~", "<cmd>vsp<CR> :Ex<CR>")
nnoremap("<leader>z", "<cmd>UndotreeToggle<CR>")
nnoremap("<leader>ga", "<cmd>G add")
nnoremap("<leader>gaa", "<cmd>G add -A<CR>")
nnoremap("<leader>gc", "<cmd>G commit<CR>")
nnoremap("<leader>gp", "<cmd>G push")
nnoremap("<leader>gpa", "<cmd>G push all<CR> :G push<CR>")
nnoremap("<leader>gs", "<cmd>G<CR>")
nnoremap("<leader>u", "<cmd>lua package.loaded.presence:update()<CR>")
nnoremap("<C-d>", "<C-d>zz")
nnoremap("<C-c>", "<C-c>zz")
nnoremap("<leader>m", "<cmd>lua require("harpoon.mark").add_file()<CR>")
nnoremap("<leader>M", "<cmd>lua require("harpoon.ui").toggle_quick_menu()<CR>")
